#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const program = require('commander');
// const download = require('download-git-repo');
// const handlebars = require('handlebars');
// const inquirer = require('inquirer');
const ora = require('ora');
const chalk = require('chalk');
const symbols = require('log-symbols');

console.log('开始构建项目');
const spinner = ora('正在运行中...');
spinner.start();

const commonPath = path.resolve(__dirname, 'common/dist');
const jzVuePath = path.resolve(__dirname, 'jzvue/dist');
const commonTargetPath = path.resolve(__dirname, 'view/common');

setTimeout(() => {
  if(Math.random() < 1) {
    fs.readdir(commonPath, (err, files) => {
      if(!err) {
        console.log('files', files);
        if(!fs.existsSync(commonTargetPath)) {
          console.log('没有view文件夹,新建view文件夹');
          fs.mkdirSync(commonTargetPath);
        }else {
          files.forEach((item, index) => {
            let item_path = path.join(commonPath, item);
            let targe_path = path.join(commonTargetPath, item);
            let temp = fs.statSync(item_path);
            if(temp.isFile()) {
              fs.copyFileSync(item_path, targe_path);
            }else if(temp.isDirectory()) {
              CopyDirectory(item_path, commonTargetPath);
            }
          })
        }
      }
    });
    spinner.succeed('运行成功');
    console.log(symbols.success ,chalk.green('项目构建成功'));
  }else {
    spinner.fail('运行失败');
    console.log(symbols.error, chalk.red('项目构建失败'));
  }
}, 3000);

function CopyDirectory(originPath, targetPath) {

}
